### ISSUE TITLE
Bug: There's no code for config 'Solo.3v3.VendorRating'

### ISSUE THREAD

**Issue by laasker** [azerothcore/mod-arena-3v3-solo-queue#3]
### Current Behaviour

In the .conf file, there's an option 'Solo.3v3.VendorRating' that should make the player be able to buy items that need arena rating through the rating from 3v3 Solo Queue if it's on, otherwise the player shouldn't be able to use rating from 3v3 Solo Queue to buy items

### Expected Behaviour

Should have a code for that option on the module

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e0bc7d73ddaae154dc113bbfa83390ffbb3040fb

### Operating system

Windows 10 x64

**Comment by pangolp** [comment]
I don't really understand how this mechanic should work. I need a little more context, because on top of that, I was always more of a pve player than a pvp player, so some things are really new to me in this regard.

**Comment by Helias** [comment]
done in the last version
